{{- if and .Values.mountSecret .Values.secretFiles ( not .Values.secretFilesSecretName ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zot.secretName" . }}
type: Opaque
data:
{{- range $key, $val := .Values.secretFiles }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
